
#pragma once

#define VIAL_KEYBOARD_UID {0xD8, 0x27, 0xC9, 0x36, 0x3D, 0x71, 0xF2, 0x13}

#define ENCODERS_PAD_A { C6, F5 }
#define ENCODERS_PAD_B { D4, F4 }

#define VIAL_COMBO_ENTRIES 2
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 2
#define DYNAMIC_KEYMAP_LAYER_COUNT 2
#define VIAL_UNLOCK_COMBO_ROWS { 0, 4 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 14 }
#define VIAL_ENCODER_DEFAULT { KC_VOLD, KC_VOLU, KC_MPRV, KC_MNXT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS }
#define TAPPING_TERM 85

// Typehud configuration
#define TYPEHUD_FILLGRAPH
#define TYPEHUD_MATRIX_COLS 15
#define TYPEHUD_MATRIX_COL_SHIFT 0
// #define TYPEHUD_MATRIX_ROTATE_90
// #define TYPEHUD_MATRIX_ROTATE_180
// #define TYPEHUD_MATRIX_ROTATE_270
